name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - lts/Hydrogen
          - node
          - 16.x
          - 14.x
          - 12.x
          - 10.x
          - 8.x
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'
          cache: npm
      - run: npm ci
      - run: npm test
